format:
  pdf:
    documentclass: scrbook
    highlight-style: arrow
    font-size: 12
    toc: true
    toc-depth: 2
    toc-title: "Content"
    lof: false
    lot: false
    color-links: true
    links-as-notes: true
    link-bibliography: false
    citecolor: "blue"
    include-in-header: [latex/preamble.tex]
    include-before-body: [latex/before_body.tex]
    geometry:
      - paperwidth=210mm
      - paperheight=297mm
      - inner=24mm
      - outer=17mm
      - top=23mm
      - bottom=24mm 
