project:
  type: book

execute:
  echo: false
  warning: false
  message: false
  fig-align: right

book:
  title: "Interpretable Machine Learning"
  subtitle: "A Guide for Making Black Box Models Explainable"
  author: "Christoph Molnar"
  output-file: iml
  cookie-consent:
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-YMSX1DV6TJ"
    anonymize-ip: true
  date:  2025-01-01 
  chapters:
    - index.qmd
    - 00.0-preface.qmd
    - 01-introduction.qmd
    - 01.2-short-stories.qmd
    - 01.3-ml-definitions.qmd
    - 02-interpretability.qmd
    - 03-datasets.qmd
    - 04.1-interpretable-models.qmd
    - 04.2-interpretable-linear.qmd
    - 04.3-interpretable-logistic.qmd
    - 04.4-interpretable-lm-extensions.qmd
    - 04.5-interpretable-tree.qmd
    - 04.6-interpretable-rules.qmd
    - 04.7-interpretable-rulefit.qmd
    - 04.8-interpretable-other.qmd
    - 05.1-agnostic.qmd
    - 06.0-example.qmd
    - global-methods.qmd
    - 05.2-agnostic-pdp.qmd
    - 05.4-agnostic-ale.qmd
    - 05.5-agnostic-interaction.qmd
    - 05-agnostic-decomposition.qmd
    - 05.6-agnostic-permfeatimp.qmd
    - 05.7-agnostic-global-surrogate.qmd
    - 06.3-example-based-proto.qmd
    - local-methods.qmd
    - what-if.qmd
    - 05.3-agnostic-ice.qmd
    - 05.8-agnostic-lime.qmd
    - 06.1-example-based-counterfactual.qmd
    - 05.8.1-agnostic-Anchors.qmd
    - 05.9-agnostic-shapley.qmd
    - 05.9b-agnostic-shap.qmd
    - 07.0-neuralnet.qmd
    - 07.1-feature-visualization.qmd
    - 07.2-feature-attribution.qmd
    - 07.3-concepts.qmd
    - 06.2-example-based-adversarial.qmd
    - 06.5-example-based-influence-fct.qmd
    - 08-future.qmd
    - 09-contribute.qmd
    - 09b-translations.qmd
    - 10-acknowledgements.qmd
    - references.qmd

bibliography: references.bib
cite-method: citeproc

format:
  epub:
    lang: en-US
    echo: false
    html-math-method: mathml
    highlight-style: printing
    always_allow_html: true
    description: "Machine learning algorithms usually operate as black boxes and it is unclear how they derived a certain decision. This book is a guide for practitioners to make machine learning decisions interpretable."
  pdf:
    documentclass: scrbook
    highlight-style: printing
    toc: true
    toc-depth: 2
    number-depth: 2
    toc-title: "Content"
    lof: false
    lot: false
    color-links: true
    links-as-notes: true
    citecolor: "blue"
    include-before-body: latex/before_body.tex
  html:
    lightbox: true
    cover-image: images/cutout.png
    include-in-header: [html/purchase.html]
    theme: cosmo
    fig-align: center



language:
  label:
    fig: "FIGURE "
    tab: "TABLE "
  ui:
    edit: "Edit"
    chapter_name: "Chapter "


